name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Verify lint
        uses: golangci/golangci-lint-action@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build SDK
        run: go build -o aleph-go
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run the tests
        run: go test ./... -v